import os

vault = os.path.abspath("obsidian_vault")

def write_note(subdir, filename, content):
    target = os.path.join(vault, subdir, filename)
    os.makedirs(os.path.dirname(target), exist_ok=True)
    with open(target, "w", encoding="utf-8") as f:
        f.write(content.strip())

# 02 Mental Models
write_note("02_Mental_Models", "Index.md", """---
tags: [mental-models, index]
---
# 🧩 Mental Models Index

* [[First_Principles]] - Deconstruct market dynamics into foundational supply & demand.
* [[Probabilistic_Thinking]] - Evaluating setups as probability distributions.
* [[Inversion]] - Anticipating how a trade plan can fail before entering.
* [[Margin_of_Safety]] - Designing entry and risk buffers.
""")

write_note("02_Mental_Models", "First_Principles.md", """---
tags: [mental-model, framework]
---
# First Principles Thinking

## Definition
First Principles thinking requires breaking down a complex problem into its most fundamental truths and building an analysis from the ground up, rather than relying on analogy or conventional wisdom.

## Application in Trading
1. **Order Flow & Liquidity**: Price moves because of an imbalance between market buy and sell orders.
2. **Pre-Market Pricing**: Opening gap is driven by global futures, ADR premia, and overnight news sentiment.
3. **Risk Management**: Risk is defined by position size multiplied by stop distance.
""")

write_note("02_Mental_Models", "Probabilistic_Thinking.md", """---
tags: [mental-model, probability]
---
# Probabilistic Thinking

## Definition
Thinking in probabilities means evaluating choices based on expected outcome distributions rather than binary certainty.

## Mathematical Formulation
Expected Value (EV) = (P_win * Reward) - (P_loss * Risk)

## Rules in ZERO Engine
* Never take a setup where EV <= 0.
* Respect the Conformal Prediction Intervals (P10-P90) generated by calibrator.py.
""")

write_note("02_Mental_Models", "Inversion.md", """---
tags: [mental-model, risk]
---
# Inversion

## Definition
Instead of asking 'How do I win this trade?', ask 'How could this trade turn into a catastrophic loss?' and systematically prevent those conditions.

## Checkpoints Before Order Execution
1. Is there an imminent high-impact macro announcement (RBI rate decision, US CPI)?
2. Am I entering near the predicted High envelope resistance?
3. Am I violating my daily max loss allocation?
""")

# 03 Cognitive Biases
write_note("03_Cognitive_Biases", "Index.md", """---
tags: [cognitive-biases, psychology, index]
---
# ⚠️ Cognitive Biases & Trader Psychology Index

* [[FOMO]] - Fear Of Missing Out.
* [[Loss_Aversion]] - Refusal to accept a small loss, resulting in huge drawdowns.
* [[Confirmation_Bias]] - Seeking only news/data that agrees with active positions.
* [[Human_Mentality_Framework]] - Comprehensive retail trader psychology guide.
""")

write_note("03_Cognitive_Biases", "FOMO.md", """---
tags: [cognitive-bias, psychology]
---
# FOMO (Fear Of Missing Out)

## Trigger
Watching price rapidly move in one direction without being in the position.

## Cognitive Distortion
Belief that the asset will continue moving indefinitely without pullback, leading to entering at market high/low.

## Mitigations in ZERO
* Wait for price to touch the calculated ATR support/resistance levels.
* Force execution via POST_ONLY or DAY LIMIT orders via [[Nautilus_Order_Types]].
""")

write_note("03_Cognitive_Biases", "Loss_Aversion.md", """---
tags: [cognitive-bias, psychology]
---
# Loss Aversion

## Definition
Psychological research shows that the pain of losing is twice as powerful as the pleasure of gaining.

## Engine Enforcement
* Pre-set [[Nautilus_Order_Types]] bracket orders (GTC OCO).
* Stop-loss is managed automatically by the Nautilus engine.
""")

write_note("03_Cognitive_Biases", "Confirmation_Bias.md", """---
tags: [cognitive-bias, psychology]
---
# Confirmation Bias

## Definition
The tendency to search for, interpret, favor, and recall information in a way that confirms pre-existing beliefs.

## Mitigation
Consult the [[Fincept_Multi_Agent_Consensus]] where bear and bull arguments are generated independently.
""")

write_note("03_Cognitive_Biases", "Human_Mentality_Framework.md", """---
tags: [psychology, framework]
---
# Human Mentality & Trader Psychology Framework

## Key Psychological Drivers
1. Greed & Impatience (Chasing gaps)
2. Fear & Hesitation (Missing valid entry signals)
3. Denial (Refusing to execute stops)
4. Revenge Trading (Doubling size after loss)

## System Constraints
The ZERO Terminal applies half-Kelly position sizing and strict CV-based calibration guardrails to remove emotion from execution.
""")

# 04 Quantitative Strategies
write_note("04_Quantitative_Strategies", "Index.md", """---
tags: [quantitative-strategies, index]
---
# ⚡ Quantitative Strategies & Execution Index

* [[Candlestick_Patterns_Encyclopedia]] - Catalog of technical candle setups.
* [[Nautilus_Order_Types]] - TIF parameters (IOC, FOK, GTC, DAY, OCO, OTO).
* [[QuantDinger_Regimes]] - Regime classification rules.
* [[Fincept_Multi_Agent_Consensus]] - Multi-analyst quantitative thesis generator.
""")

write_note("04_Quantitative_Strategies", "Candlestick_Patterns_Encyclopedia.md", """---
tags: [candlesticks, technicals]
---
# Candlestick Patterns Encyclopedia

## Key Patterns Recognized
* **Bullish Engulfing**: Prior red body completely enclosed by large green candle. High reversal probability at support.
* **Hammer / Pinbar**: Long lower shadow with small upper body. Rejection of low prices.
* **Doji**: Open and Close virtually identical. Indicates indecision near range boundaries.
* **Shooting Star**: Long upper shadow at resistance indicating rejection of higher prices.
""")

write_note("04_Quantitative_Strategies", "Nautilus_Order_Types.md", """---
tags: [nautilus, execution, order-types]
---
# Nautilus Order Types & Contingency Matrix

## Time-In-Force (TIF)
* **IOC (Immediate Or Cancel)**: Fills instantly or cancels remaining.
* **FOK (Fill Or Kill)**: Entire order must fill immediately or be killed.
* **GTC (Good 'Til Cancelled)**: Active until explicitly cancelled.
* **DAY**: Active only for current market session.

## Contingency Chains
* **OCO (One-Cancels-Other)**: Dual exit bracket (Take Profit Limit + Stop Loss Stop).
* **OTO (One-Triggers-Other)**: Entry order fill automatically places the exit bracket.
""")

write_note("04_Quantitative_Strategies", "QuantDinger_Regimes.md", """---
tags: [quantdinger, regimes]
---
# QuantDinger Market Regimes

1. **TRENDING_BULLISH**: Gap Up > 0.35%, PCR >= 1.05, Positive Sentiment.
2. **TRENDING_BEARISH**: Gap Down < -0.35%, PCR <= 0.95, Negative Sentiment.
3. **VOLATILE_RANGEBOUND**: VIX > 22.0 or Range > 2.2%.
4. **MACRO_SHOCK**: Sentiment > 0.4 & VIX > 18.0.
5. **LOW_VOL_SQUEEZE**: Range < 1.0% & VIX < 14.0.
""")

write_note("04_Quantitative_Strategies", "Fincept_Multi_Agent_Consensus.md", """---
tags: [fincept, consensus, multi-agent]
---
# Fincept Multi-Agent Consensus Framework

Simulates a 3-agent quant desk:
1. **Quant Strategist**: Evaluates technical momentum, trend, and alpha signals.
2. **Risk Analyst**: Applies half-Kelly sizing and computes maximum drawdown risk.
3. **Microstructure Specialist**: Analyzes spreads, liquidity depth, and order book imbalance.
""")

# 05 AI Memory
write_note("05_AI_Memory", "Index.md", """---
tags: [ai-memory, skills, index]
---
# 🤖 AI Memory & Executable Skills Index

* [[AI_System_Capabilities_Executable_Skills]] - MCP, RAG, LoRA, Quantization, Embeddings, Vector DBs, KV Cache, RLHF, AGI.
* [[Claude_Obsidian_Integration_Plan]] - Bidirectional knowledge sync specification.
* [[ZERO_Engine_Knowledge_Graph]] - Knowledge map of the ZERO system.
""")

write_note("05_AI_Memory", "AI_System_Capabilities_Executable_Skills.md", """---
tags: [ai-capabilities, skills, system-design]
---
# Conceptual Framework: AI System Capabilities as Executable Skills

## 1. I/O Engine Protocols
* **MCP (Model Context Protocol)**: Stateful JSON-RPC protocol abstracting tools, resources, and prompts.
* **RAG (Retrieval-Augmented Generation)**: Grounding LLM prompts with external vector stores.

## 2. State & Parametric Modifiers
* **LoRA (Low-Rank Adaptation)**: Factorized weight update matrices W = W_0 + (alpha/r)*(B * A).
* **Quantization**: Mapping FP32/FP16 tensors to FP8/INT4 to optimize VRAM and compute throughput.

## 3. Memory Geometry
* **Embeddings**: Dense high-dimensional vector representations.
* **Vector Databases**: HNSW & IVF indexing for low-latency k-NN search.
* **Context Windows**: Memory sequence buffer bounds.

## 4. Training & Scaling Targets
* **RLHF / DPO**: Aligning model outputs with human preference.
* **AGI**: Multi-domain cognitive flexibility.

## 5. Inference Mechanics
* **KV Cache**: Prefill and Decode phase attention caching (PagedAttention, FlashAttention).
* **Multimodal**: Latent space alignment of text, image, and voice inputs.
""")

write_note("05_AI_Memory", "Claude_Obsidian_Integration_Plan.md", """---
tags: [integration, obsidian, zero-engine]
---
# Claude Obsidian Integration Plan

## Bidirectional Knowledge Flow
1. **Engine to Obsidian**: `engine/obsidian_sync.py` automatically writes daily predictions to `01_Daily_Logs/YYYY-MM-DD.md`.
2. **Obsidian to Engine**: `engine/zero_engine_kb.py` reads user notes from `02_Mental_Models`, `03_Cognitive_Biases`, `04_Quantitative_Strategies`, and `05_AI_Memory` into Gemini AI system context.
""")

write_note("05_AI_Memory", "ZERO_Engine_Knowledge_Graph.md", """---
tags: [knowledge-graph, system]
---
# ZERO Engine Knowledge Graph

Node Graph representing the interaction between:
- Data Ingestion (GIFT Nifty, Options Chain, RSS Feeds)
- Calibrator & Matrix (Conformal bounds + bias correction)
- Quant Engines (Nautilus, Fincept, QuantDinger)
- Obsidian Second Brain (Mental models + trade logs)
""")

# 06 System Architecture
write_note("06_System_Architecture", "Index.md", """---
tags: [architecture, index]
---
# 🏛️ System Architecture Index

* [[ZERO_v1.0_System_Overview]] - Comprehensive technical layout of ZERO Terminal v1.0.
""")

write_note("06_System_Architecture", "ZERO_v1.0_System_Overview.md", """---
tags: [architecture, zero-v1]
---
# ZERO v1.0 System Overview

ZERO is built on 4 core layers:
1. **Ingestion Layer** (`data/`): Options chain, news sentiment, historical statistics.
2. **Quantitative Engine Core** (`engine/`): Nautilus order engine, Fincept platform, QuantDinger, Walk-Forward backtester, Calibrator.
3. **AI Brain & Knowledge Layer** (`engine/zero_engine_kb.py` & `obsidian_vault/`): Dynamic RAG system.
4. **Streamlit UI Terminal** (`app.py` & `ui/`): Digital core dashboard.
""")

# 01 Daily Logs Index
write_note("01_Daily_Logs", "Index.md", """---
tags: [daily-logs, index]
---
# 📅 Daily Logs & Predictions Index

This directory automatically receives daily pre-market predictions generated by ZERO Terminal.
""")

print("SUCCESSFULLY POPULATED OBSIDIAN VAULT!")
